export const SET_PROJECTS = 'SET_PROJECTS';
export const SELECT_PROJECT = 'SELECT_PROJECT';
export const SET_SELECTED_PROJECTS = 'SET_SELECTED_PROJECTS';

export const SUBMIT_VOTE = 'SUBMIT_VOTE';
export const SHOW_STATS = 'SHOW_STATS';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
